#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.yangtaibang.domain.yangtaibang.feed
  mapperLocations: classpath:src/main/java/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/yangtaibang
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver