package com.yangtaibang.domain.yangtaibang.feed;

import com.yangtaibang.domain.yangtaibang.feed.feedsActionCount;
import com.yangtaibang.domain.yangtaibang.feed.feedsActionCountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface feedsActionCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds_action_count
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    int countByExample(feedsActionCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds_action_count
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    int deleteByExample(feedsActionCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds_action_count
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds_action_count
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    int insert(feedsActionCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds_action_count
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    int insertSelective(feedsActionCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds_action_count
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    List<feedsActionCount> selectByExample(feedsActionCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds_action_count
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    feedsActionCount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds_action_count
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    int updateByExampleSelective(@Param("record") feedsActionCount record, @Param("example") feedsActionCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds_action_count
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    int updateByExample(@Param("record") feedsActionCount record, @Param("example") feedsActionCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds_action_count
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    int updateByPrimaryKeySelective(feedsActionCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feeds_action_count
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    int updateByPrimaryKey(feedsActionCount record);
}