package com.yangtaibang.domain.yangtaibang.feed;

public class feedsActionCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeds_action_count.id
     *
     * @mbggenerated Wed Nov 14 16:42:54 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeds_action_count.num_cmt
     *
     * @mbggenerated Wed Nov 14 16:42:54 CST 2018
     */
    private Integer numCmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeds_action_count.num_good
     *
     * @mbggenerated Wed Nov 14 16:42:54 CST 2018
     */
    private Integer numGood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeds_action_count.num_repost
     *
     * @mbggenerated Wed Nov 14 16:42:54 CST 2018
     */
    private Integer numRepost;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeds_action_count.id
     *
     * @return the value of feeds_action_count.id
     *
     * @mbggenerated Wed Nov 14 16:42:54 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeds_action_count.id
     *
     * @param id the value for feeds_action_count.id
     *
     * @mbggenerated Wed Nov 14 16:42:54 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeds_action_count.num_cmt
     *
     * @return the value of feeds_action_count.num_cmt
     *
     * @mbggenerated Wed Nov 14 16:42:54 CST 2018
     */
    public Integer getNumCmt() {
        return numCmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeds_action_count.num_cmt
     *
     * @param numCmt the value for feeds_action_count.num_cmt
     *
     * @mbggenerated Wed Nov 14 16:42:54 CST 2018
     */
    public void setNumCmt(Integer numCmt) {
        this.numCmt = numCmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeds_action_count.num_good
     *
     * @return the value of feeds_action_count.num_good
     *
     * @mbggenerated Wed Nov 14 16:42:54 CST 2018
     */
    public Integer getNumGood() {
        return numGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeds_action_count.num_good
     *
     * @param numGood the value for feeds_action_count.num_good
     *
     * @mbggenerated Wed Nov 14 16:42:54 CST 2018
     */
    public void setNumGood(Integer numGood) {
        this.numGood = numGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeds_action_count.num_repost
     *
     * @return the value of feeds_action_count.num_repost
     *
     * @mbggenerated Wed Nov 14 16:42:54 CST 2018
     */
    public Integer getNumRepost() {
        return numRepost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeds_action_count.num_repost
     *
     * @param numRepost the value for feeds_action_count.num_repost
     *
     * @mbggenerated Wed Nov 14 16:42:54 CST 2018
     */
    public void setNumRepost(Integer numRepost) {
        this.numRepost = numRepost;
    }

    @Override
    public String toString() {
        return "feedsActionCount{" +
                "id=" + id +
                ", numCmt=" + numCmt +
                ", numGood=" + numGood +
                ", numRepost=" + numRepost +
                '}';
    }

}