package com.yangtaibang.domain.yangtaibang.feed;

public class FeedDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeds_detail.id
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeds_detail.unionID
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    private String unionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeds_detail.retid
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    private Long retid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeds_detail.ip
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeds_detail.dateline
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    private Integer dateline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeds_detail.mobi_model
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    private String mobiModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeds_detail.state
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeds_detail.imgs
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    private String imgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeds_detail.content
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feeds_detail.exts
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    private String exts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeds_detail.id
     *
     * @return the value of feeds_detail.id
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeds_detail.id
     *
     * @param id the value for feeds_detail.id
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeds_detail.unionID
     *
     * @return the value of feeds_detail.unionID
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeds_detail.unionID
     *
     * @param unionid the value for feeds_detail.unionID
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeds_detail.retid
     *
     * @return the value of feeds_detail.retid
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public Long getRetid() {
        return retid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeds_detail.retid
     *
     * @param retid the value for feeds_detail.retid
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public void setRetid(Long retid) {
        this.retid = retid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeds_detail.ip
     *
     * @return the value of feeds_detail.ip
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeds_detail.ip
     *
     * @param ip the value for feeds_detail.ip
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeds_detail.dateline
     *
     * @return the value of feeds_detail.dateline
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public Integer getDateline() {
        return dateline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeds_detail.dateline
     *
     * @param dateline the value for feeds_detail.dateline
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public void setDateline(Integer dateline) {
        this.dateline = dateline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeds_detail.mobi_model
     *
     * @return the value of feeds_detail.mobi_model
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public String getMobiModel() {
        return mobiModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeds_detail.mobi_model
     *
     * @param mobiModel the value for feeds_detail.mobi_model
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public void setMobiModel(String mobiModel) {
        this.mobiModel = mobiModel == null ? null : mobiModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeds_detail.state
     *
     * @return the value of feeds_detail.state
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeds_detail.state
     *
     * @param state the value for feeds_detail.state
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeds_detail.imgs
     *
     * @return the value of feeds_detail.imgs
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public String getImgs() {
        return imgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeds_detail.imgs
     *
     * @param imgs the value for feeds_detail.imgs
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public void setImgs(String imgs) {
        this.imgs = imgs == null ? null : imgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeds_detail.content
     *
     * @return the value of feeds_detail.content
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeds_detail.content
     *
     * @param content the value for feeds_detail.content
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feeds_detail.exts
     *
     * @return the value of feeds_detail.exts
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public String getExts() {
        return exts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feeds_detail.exts
     *
     * @param exts the value for feeds_detail.exts
     *
     * @mbggenerated Sun Nov 18 11:22:32 CST 2018
     */
    public void setExts(String exts) {
        this.exts = exts == null ? null : exts.trim();
    }
}